source 'https://git.coding.net/wubianxiaoxian/SKFFMPrivateLib.git'
source 'https://github.com/CocoaPods/Specs.git'  #官方仓库的地址


use_frameworks!

target 'OneVc_Example' do
  pod 'OneVc', :path => '../'

  target 'OneVc_Tests' do
    inherit! :search_paths

    
  end
end
